### ISSUE TITLE
Conflicting declarations

### ISSUE THREAD

**Issue by theapache64** [wuseal/JsonToKotlinClass#297] opened 2020-05-26 08:19 UTC
**Input**
```json
{
  "Data": [
    {
      "name": "MEDICAL CONDITION",
      "show": true,
      "id": 1
    },
    {
      "name": "LAB TEST REPORT",
      "show": true,
      "id": 9,
      "type": [
        {
          "id": 21,
          "name": "CULTURE REPORT",
          "show": true
        }
      ]
    }
  ]
}
```

**Expected Output**

```kotlin
data class MyModel(
    val data: List<Data>
) {
    data class Data(
        val id: Int, // 1
        val name: String, // MEDICAL CONDITION
        val show: Boolean, // true
        val type: List<Type>
    ) {
        data class Type(
            val id: Int, // 21
            val name: String, // CULTURE REPORT
            val show: Boolean // true
        )
    }
} 
```
**Actual Output**

```kotlin
data class MyModel(
    val Data: List<Data>
) {
    data class Data(
        val id: Int, // 1
        val name: String, // MEDICAL CONDITION
        val show: Boolean, // true
        val type: List<Type>
    ) {
        data class Type(
            val id: Int, // 21
            val name: String, // CULTURE REPORT
            val show: Boolean // true
        )
    }
} 
```

**What's wrong?**
![](https://i.imgur.com/XsIEgIz.png)

Source : https://plugins.jetbrains.com/plugin/9960-json-to-kotlin-class-jsontokotlinclass-/reviews#review=26525

**Comment by wuseal** [comment] 2020-05-27 02:38
OMG, may cause new bug

**Comment by hanshengjian** [comment] 2020-07-26 00:06
The names of Class Model‘s properties is the same with the names of the json string's properties defautly.So in this situation,I propose add a gson's annotaion such as "@SerializedName("Data")".New Class Model from this json string like this

`data class MyModel(
    @SerializedName("Data")
    val `data`: List<Data>
) {
    data class Data(
        val id: Int,
        val name: String,
        val show: Boolean,
        val type: List<Type>
    ) {
        data class Type(
            val id: Int,
            val name: String,
            val show: Boolean
        )
    }
}`

**Comment by hanshengjian** [comment] 2020-07-26 00:21
> **Input**
> 
> ```json
> {
>   "Data": [
>     {
>       "name": "MEDICAL CONDITION",
>       "show": true,
>       "id": 1
>     },
>     {
>       "name": "LAB TEST REPORT",
>       "show": true,
>       "id": 9,
>       "type": [
>         {
>           "id": 21,
>           "name": "CULTURE REPORT",
>           "show": true
>         }
>       ]
>     }
>   ]
> }
> ```
> 
> **Expected Output**
> 
> ```kotlin
> data class MyModel(
>     val data: List<Data>
> ) {
>     data class Data(
>         val id: Int, // 1
>         val name: String, // MEDICAL CONDITION
>         val show: Boolean, // true
>         val type: List<Type>
>     ) {
>         data class Type(
>             val id: Int, // 21
>             val name: String, // CULTURE REPORT
>             val show: Boolean // true
>         )
>     }
> } 
> ```
> 
> **Actual Output**
> 
> ```kotlin
> data class MyModel(
>     val Data: List<Data>
> ) {
>     data class Data(
>         val id: Int, // 1
>         val name: String, // MEDICAL CONDITION
>         val show: Boolean, // true
>         val type: List<Type>
>     ) {
>         data class Type(
>             val id: Int, // 21
>             val name: String, // CULTURE REPORT
>             val show: Boolean // true
>         )
>     }
> } 
> ```
> 
> **What's wrong?**
> ![](https://camo.githubusercontent.com/fd71b5c623d5a965fdc785309ed90088a13ed960/68747470733a2f2f692e696d6775722e636f6d2f5873494567497a2e706e67)
> 
> Source : https://plugins.jetbrains.com/plugin/9960-json-to-kotlin-class-jsontokotlinclass-/reviews#review=26525

I propose add a serialization field annotation,because serializing a json string like that  when the class model has't  corresponding attribute name will occur null value in the serialization  object.

**Comment by wuseal** [comment] 2021-04-25 03:21
Yes， This is not a bug, It's the expected behavior , will close this issue @theapache64

**Closed by wuseal** 2021-04-25 03:21 UTC
Labels: L2, bug
