### ISSUE TITLE
Class generation doesn't work with JSONSchema HasuraMetadataV2.schema.json

### ISSUE THREAD

**Issue by beepsoft** [wuseal/JsonToKotlinClass#314] opened 2020-11-17 15:47 UTC
I tried to generate Kotlin data classes based on this schema:

https://raw.githubusercontent.com/hasura/graphql-engine/master/contrib/metadata-types/src/metadata-schemas/HasuraMetadataV2.schema.json

The result is always an empty file (with just a `package ...` at the top).

Does this file has some JSONSchema construct that is not supported? Or what could be the problem?

**Comment by wuseal** [comment] 2020-11-17 16:03
@beepsoft @TedZeng Pls look at it

**Comment by wuseal** [comment] 2020-11-18 03:31
@TedZen Pls look at it.

**Comment by TedZen** [comment] 2020-11-18 05:58
@beepsoft Thank you to feed back, I'll check this out

**Comment by beepsoft** [comment] 2020-11-18 08:09
@TedZen Thanks!

**Comment by wuseal** [comment] 2021-04-25 03:07
Because the json Only contains `Definition`, So no class generated, maybe you should update the structure 
@beepsoft

**Comment by wuseal** [comment] 2021-05-18 02:56
Not a bug, Close it

**Closed by wuseal** 2021-05-18 02:56 UTC
