### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: 4, Size: 4

### ISSUE THREAD

**Issue by wuseal** [wuseal/JsonToKotlinClass#91] opened 2018-12-09 07:12 UTC
PluginVersion:2.3.0
user: 8823aa17-b73b-4bab-a5a0-1a65cd652802
createTime: 2018-12-04 16:42:12 星期二
```
java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at wu.seal.jsontokotlin.KotlinDataClassMaker.renameDuplicateClassNames(KotlinDataClassMaker.kt:28)
	at wu.seal.jsontokotlin.KotlinDataClassMaker.makeKotlinDataClasses(KotlinDataClassMaker.kt:19)
	at wu.seal.jsontokotlin.KotlinDataClassCodeMaker.makeKotlinDataClassCode(KotlinDataClassCodeMaker.kt:24)
	at wu.seal.jsontokotlin.KotlinDataClassCodeMaker.makeKotlinDataClassCode(KotlinDataClassCodeMaker.kt:12)
	at wu.seal.jsontokotlin.MakeKotlinClassAction.insertKotlinCode(MakeKotlinClassAction.kt:129)
	at wu.seal.jsontokotlin.MakeKotlinClassAction.actionPerformed(MakeKotlinClassAction.kt:69)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:215)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:232)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:974)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:964)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.lambda$onChosen$0(PopupFactoryImpl.java:958)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.ui.popup.AbstractPopup.lambda$null$7(AbstractPopup.java:1396)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
Error Json String:
```js
{
  "test": {
    "value": {
      "key1": "fdf"
    }
  },
  "value": {
    "key2": "nfj"
  }
}
```

**Comment by kezhenxu94** [comment] 2018-12-21 15:32
I cannot reproduce this bug, we do not have this method in version 2.3.0:

```
at wu.seal.jsontokotlin.KotlinDataClassMaker.renameDuplicateClassNames(KotlinDataClassMaker.kt:28)
```

is this reported when @Karthik2007 was fixing issue #82 ?

@wuseal maybe we will need to disable bug reporting in non-production mode

**Comment by Karthik2007** [comment] 2018-12-21 17:02
@kezhenxu94   @wuseal  reported json is the one I used for testing... so it should be...

**Comment by kezhenxu94** [comment] 2018-12-22 03:10
Close it

**Closed by kezhenxu94** 2018-12-22 03:10 UTC
